<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Detail_alat_model extends CI_Model
{

    public $table = 'detail_alat';
    public $id = 'id_detail_alat';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_detail_alat', $q);
	$this->db->or_like('id_alat', $q);
	$this->db->or_like('id_kondisi', $q);
	$this->db->or_like('jumlah_kondisi', $q);
	$this->db->or_like('tanggal_kondisi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    function total_baik() {
        $this->db->where('id_kondisi','1');
        $this->db->select_sum('jumlah_kondisi');
        $this->db->from($this->table);
        return $this->db->get()->row();
    }

    function total_rusak() {
        $this->db->where('id_kondisi','2');
        $this->db->select_sum('jumlah_kondisi');
        $this->db->from($this->table);
        return $this->db->get()->row();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('kondisi', 'kondisi.id_kondisi=detail_alat.id_kondisi');
        $this->db->join('alat_medis', 'alat_medis.id_alat=detail_alat.id_alat');
        $this->db->like('id_detail_alat', $q);
	$this->db->or_like('detail_alat.id_alat', $q);
	$this->db->or_like('detail_alat.id_kondisi', $q);
	$this->db->or_like('jumlah_kondisi', $q);
	$this->db->or_like('tanggal_kondisi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Detail_alat_model.php */
/* Location: ./application/models/Detail_alat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-20 17:10:13 */
/* http://harviacode.com */