<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Puskesmas_model extends CI_Model
{

    public $table = 'puskesmas';
    public $id = 'id_puskesmas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

     function get_list(){
        $query=$this->db->get('puskesmas');
        return $query;
     }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_puskesmas', $q);
	$this->db->or_like('nama_puskesmas', $q);
    $this->db->or_like('keterangan_puskesmas', $q);
    $this->db->or_like('alamat_puskesmas', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_puskesmas', $q);
	$this->db->or_like('nama_puskesmas', $q);
    $this->db->or_like('keterangan_puskesmas', $q);
    $this->db->or_like('alamat_puskesmas', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Jenis_model.php */
/* Location: ./application/models/Jenis_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-20 17:10:13 */
/* http://harviacode.com */